[project]
name = "workshop-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "akshara gurjar", email = "aksharag406@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
workshop-ml = "workshop_ml:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
